name = "filament"   # match what the CI expects per your log
main = "src/index.ts"
compatibility_date = "2025-09-01"

# Bind your KV namespace
kv_namespaces = [
  { binding = "PRICES", id = "<KV_NAMESPACE_ID>", preview_id = "<KV_PREVIEW_ID>" }
]

# Optional: secure manual update endpoint
[vars]
UPDATE_TOKEN = "change-me"

# Auto refresh every 6 hours (UTC)
[triggers]
crons = ["0 */6 * * *"]
